/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cloud_logic_custom": [
        {
            "name": "AdminQueries",
            "endpoint": "https://33p5obpfg1.execute-api.us-east-1.amazonaws.com/stage",
            "region": "us-east-1"
        }
    ],
    "aws_appsync_graphqlEndpoint": "https://a7jjgxtjt5cxbd5l6lthanevte.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "AWS_IAM",
    "aws_cognito_identity_pool_id": "us-east-1:444dda66-af89-47d0-8350-c8a423b346ee",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_vrd5uG6QY",
    "aws_user_pools_web_client_id": "9b2ucul3plm60gs3rr4jisb9f",
    "oauth": {},
    "aws_cognito_username_attributes": [
        "EMAIL"
    ],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL",
        "NAME"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_user_files_s3_bucket": "s3storagebybus193751-stage",
    "aws_user_files_s3_bucket_region": "us-east-1"
};


export default awsmobile;
